baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Farrel Beso'
theme = "dream"

[params]
showTableOfContents = true
showPrevNextPost = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

    [markup.goldmark.parser.attribute]
    block = true