baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Farrel Beso'
theme = "dream"

[params]

showTableOfContents = true
showPrevNextPost = true
showSummaryCoverInPost = true
imageZoomableInPost = true

lightTheme = "emerald"
darkTheme = "forest"

author = "Farrel Beso"
avatar = "img/personal/avatar.jpg"
description = "My Blog"
headerTitle = "Farrel's Blog"
email = "farrelbeso@gmail.com"
siteStartYear = 2025

utterancesRepo = "https://vfaabeso.github.io/blog/"

# [params.advanced]
# customCSS = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

    [markup.goldmark.parser.attribute]
    block = true

# [services]
# [services.disqus]
# shortname = "..."

[caches]
  [caches.images]
    dir = ':cacheDir/images'